In [17]:
import numpy as np
import matplotlib.pyplot as plt

# Parameters
M = 4  # Order of QAM (e.g., 16-QAM)
symbol_rate = 1 # Symbols per second
sample_rate = 1 # Samples per second
time = 10  # Signal duration in seconds

In [18]:
# Generate random symbols# Generate random symbols
num_symbols = int(symbol_rate * time)
symbols = np.random.randint(0, M, num_symbols)  # Random indices for QAM symbols

print(num_symbols)
print(symbols)
I_vals = 2 * (np.arange(np.sqrt(M)) - (np.sqrt(M) - 1) / 2)
Q_vals = 2 * (np.arange(np.sqrt(M)) - (np.sqrt(M) - 1) / 2)
print(I_vals)
print(Q_vals)

10
[2 1 1 2 3 3 3 1 2 1]
[-1.  1.]
[-1.  1.]


In [19]:
# Map symbols to QAM_values
constellation = np.array([[i + 1j * q for q in Q_vals] for i in I_vals]).flatten()

qam_modulated_signal = constellation[symbols]
print(constellation)
print(qam_modulated_signal)

[-1.-1.j -1.+1.j  1.-1.j  1.+1.j]
[ 1.-1.j -1.+1.j -1.+1.j  1.-1.j  1.+1.j  1.+1.j  1.+1.j -1.+1.j  1.-1.j
 -1.+1.j]


In [20]:
# Generate time-domain waveform
samples_per_symbol = int(sample_rate / symbol_rate)
t = np.arange(num_symbols * samples_per_symbol) / sample_rate
carrier_I = np.real(qam_modulated_signal.repeat(samples_per_symbol))
carrier_Q = np.imag(qam_modulated_signal.repeat(samples_per_symbol))
carrier_waveform = carrier_I * np.cos(2 * np.pi * symbol_rate * t) - carrier_Q * np.sin(2 * np.pi * symbol_rate * t)

In [21]:
print(samples_per_symbol)
print(t)
print(carrier_I)
print(carrier_Q)
print(carrier_waveform)

1
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 1. -1. -1.  1.  1.  1.  1. -1.  1. -1.]
[-1.  1.  1. -1.  1.  1.  1.  1. -1.  1.]
[ 1. -1. -1.  1.  1.  1.  1. -1.  1. -1.]


In [22]:
# Add noise
SNR_dB = 20  # Signal-to-noise ratio in dB
SNR = 10 ** (SNR_dB / 10)
noise_power = np.var(carrier_waveform) / SNR
noise = np.sqrt(noise_power) * np.random.randn(len(carrier_waveform))
received_signal = carrier_waveform + noise
print(carrier_waveform)

[ 1. -1. -1.  1.  1.  1.  1. -1.  1. -1.]


In [23]:
# Demodulation
received_I = received_signal * np.cos(2 * np.pi * symbol_rate * t)
received_Q = -received_signal * np.sin(2 * np.pi * symbol_rate * t)
# Symbol detection
received_constellation = received_I + 1j * received_Q
print(received_constellation)

[ 1.00078559+0.00000000e+00j -1.12773465-2.76215326e-16j
 -0.76594378-3.75204241e-16j  1.09180741+8.02247073e-16j
  1.06065446+1.03914167e-15j  1.00957471+1.23637244e-15j
  1.17257274+1.72318495e-15j -0.85063685-1.45842157e-15j
  0.98368647+1.92746958e-15j -1.09782282-2.42000136e-15j]


In [24]:
detected_symbols = np.argmin(np.abs(received_constellation[:, None] - constellation[None, :]), axis=1)
print(detected_symbols)


[2 0 0 3 3 3 3 0 3 0]


In [25]:
print(symbols)

[2 1 1 2 3 3 3 1 2 1]
